apiVersion: batch/v1
kind: Job
metadata:
  name: fio-runner
  namespace: px-bench
spec:
  template:
    metadata:
      labels:
        app: fio
        px-bench: "true"
    spec:
      restartPolicy: Never
      serviceAccountName: px-bench
      containers:
      - name: fio
        image: dmonakhov/alpine-fio
        command: ["/bin/sh","-lc","chmod +x /runner/runner.sh && /runner/runner.sh"]
        securityContext:
          privileged: true
        env:
        - name: HOURS
          value: "1"
        - name: RUNTIME_PER_JOB
          value: ""
        - name: SIZE
          value: "1GiB"
        - name: SC_NAME
          value: "single"
        - name: MODE
          value: "single"
        - name: RESULTS_DIR
          value: "/results"
        - name: KEEP_ALIVE
          value: "false"
        volumeMounts:
        - mountPath: /results
          name: results
        - mountPath: /fiocfg
          name: fiocfg
        - mountPath: /runner
          name: runner
        - mountPath: /data
          name: test-volume
      volumes:
      - name: results
        persistentVolumeClaim:
          claimName: px-bench-results
      - name: fiocfg
        configMap:
          name: fiocfg
      - name: runner
        configMap:
          name: px-bench-runner
          defaultMode: 0755
      - name: test-volume
        emptyDir: {}

