apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: px-bench-results
  namespace: px-bench
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  # IMPORTANT: set to a Portworx RWX-capable StorageClass in your cluster
  # storageClassName: px-sharedv4-sc

